name: publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: NPM config
        run: |
          npm config set //registry-lpm.listenai.com/:_password ${{ secrets.LPM_ADMIN_TOKEN }}
          npm config set //registry-lpm.listenai.com/:username lpmadmin
          npm config set //registry-lpm.listenai.com/:email lpm.admin@listenai.com
          npm config set //registry-lpm.listenai.com/:always-auth true
      - name: Install dependencies
        run: npm install --ignore-scripts --registry=https://registry-lpm.listenai.com

      - name: Publish (latest)
        run: npm publish --registry=https://registry-lpm.listenai.com
